PRINT 'Populating ProcurementMethods'

SET IDENTITY_INSERT [dbo].[ProcurementMethods] ON
GO


MERGE INTO [dbo].[ProcurementMethods] as Env
	USING ( VALUES
	 
	(1,'H','Agency Invitation to Bid','C',1,1)
,(2,'H1','Agency Invitation to Bid for Public Property And Publicly Owned Buildings','C',	1,	1)
,(3,'J','Agency Invitation to Negotiate','C',	1,	1)
,(4,'J1','Agency Invitation to Negotiate for Public Property And Publicly Owned Buildings','C',	1,	1)
,(5,'K','Agency negotiated after receiving fewer than two responsive offers to a competitive procurement','C',	1,	1)
,(6,'I','Agency Request for Proposal','C',	1,	1)
,(7,'I1','Agency Request for Proposal for Public Property And Publicly Owned Buildings','C',	1,	1)
,(8,'C','Alternate contract source - Purchase made from contracts let by the Fed. Gov., another state, or a political subdivision for commodities and contract services if determined to be cost-effective and in the best interest of the state','C',	1,	1)
,(9,'Q','Consultants Competitive Negotiation Act','C',	1,	1)
,(10,'26','DEP Exempt, Division of Recreation and Parks may grant privileges, leases, concessions and permits for the use of land for the accommodation of visitors in the various parks, monuments and memorials','E',	0,	0)
,(11,'31','DEP Exempt, Inland Protection Trust Fund Early Detection Incentive Program','E',	0,	0)
,(12,'30','DEP Exempt, Inland Protection Trust Fund Petroleum Cleanup Participation Program','E',	0,	0)
,(13,'29','DEP Exempt, Inland Protection Trust Fund Reimbursement-review Contracts','E',	0,	0)
,(14,'28','DEP Exempt, Preapproved Advanced Cleanup','E',	0,	0)
,(15,'27','DEP Exempt, Preapproved Site Rehabilitation Program','E',	0,	0)
,(16,'32','DEP State Restoration Funding Assistance','C',	0,	0)
,(17,'H3','DOT Invitation to Bid','C',	0,	0)
,(18,'I3','DOT Request for Proposal','C',	0,	0)
,(19,'O','Emergency procurement','E',	1,	1)
,(20,'O1','Emergency Purchases for Public Property And Publicly Owned Buildings','E',	1,	1)
,(21,'O2','Emergency Purchases Per Governors Executive Order','E',	1,	1)
,(22,'V','Exempt, Academic program review','E',	0,	1)
,(23,'0','Exempt, Adoption Placement Services Licensed by DCF','E',	0,	1)
,(24,'U','Exempt, Artistic services','E',	0,	1)
,(25,'X','Exempt, Auditing Services','E',	0,	1)
,(26,'R','Exempt, CHD Use of County Procurement Standards','E',	0,	1)
,(27,'S','Exempt, Commodities purchased for resale','E',	0,	1)
,(28,'W2','Exempt, Continuing education and events paid for by collected','E',	0,	1)
,(29,'10','Exempt, Department of Citrus advertising and promotional items','E',	0,	1)
,(30,'20','Exempt, Division of Blind Services; Rehabilitation Council for the Blind purchase','E',	0,	1)
,(31,'6','Exempt, Family Placement','E',0,	1)
,(32,'9A','Exempt, Federal or state law prescribes with whom the agency must contract','E',	0,	1)
,(33,'3','Exempt, Health services, including examination, diagnosis, treatment, prevention, medical consultation or administration','E',	0,	1)
,(34,'W1','Exempt, Lectures by individuals','E',	0,	1)
,(35,'2','Exempt, Legal services, including Attorney, paralegal, expert witness, appraisal and mediator services','E',	0,	1)
,(36,'5','Exempt, Medicaid services','E',	0,	1)
,(37,'Y','Exempt, Payment of Membership Dues','E',	0,	1)
,(38,'1','Exempt, Prescriptive assistive devices','E',	0,	1)
,(39,'7','Exempt, Prevention services related to mental health, substance and child abuse, shelters/runaways, by non-profits','E',	0,	1)
,(40,'Z','Exempt, Professional Examinations','E',	0,	1)
,(41,'24','Exempt, Propane Collected Assessments','E',	0,	1)
,(42,'N','Exempt, Purchase made from PRIDE - Department of Corrections; prison industry programs','E',	0,	1)
,(43,'M','Exempt, Purchase made from RESPECT - Qualified nonprofit agency for the blind or for the other severely handicapped','E',	0,	1)
,(44,'T','Exempt, Regulated utilities and government franchised and public communications, except long distance telecommunications services or governmental franchise SVCCS','E',	0,	1)
,(45,'L','Exempt, Services or Commodities provided by Governmental Agencies, including contract with independent, non-profit college or university within the state','E',	0,	1)
,(46,'4','Exempt, Services to persons w/ mental/physical disabilities by non-profit corporations','E',	0,	1)
,(47,'22','Exempt, Special contracts with charitable youth organizations','E',	0,	1)
,(48,'12','Exempt, Specialized equipment, devices and technology, including low-vision aids for Vision Impaired Persons','E',	0,	1)
,(49,'8','Exempt, Training and education services','E',	0,	1)
,(50,'23','Exempt, Transportation for the Disadvantaged','E',	0,	1)
,(51,'F1','Informal quote below the bidding thresholds for Public Property And Publicly Owned Buildings of $200,000','C',	1,	1)
,(52,'F','Informal quoted purchase not exceeding Category Two - Request for Quotes','C',	1,	1)
,(53,'35','Leases having a term of less than 120 consecutive days','E',	1,	1)
,(54,'16','Lottery - Competitive Quote','C',	0,	0)
,(55,'15','Lottery - Competitive Solicitation','C',	0,	0)
,(56,'18','Lottery - Cooperative Agreement','C',	0,	0)
,(57,'17','Lottery – Emergency Purchase','E',	0,	0)
,(58,'14','Lottery – Single Source Purchase of Single Source Commodities or Services','E',	0,	0)
,(59,'11','Lottery Procurement','C',	0,	0)
,(60,'33','No Cost Procurement','E',	1,	1)
,(61,'E','Purchase under $2,500','E',	1,	1)
,(62,'9B','Rate of payment is established during the appropriation process','E',	1,	1)
,(63,'25','Request for Application, method of competitively awarding State Federal grants to non-profits and other governmental entities','C',	1,	1)
,(64,'34','Revenue Generating Procurement','E',	1,	1)
,(65,'21','Settlement Agreement','E',	0,	1)
,(66,'G','Single source $2,500 or greater, not to exceed Category Two','E',	1,	1)
,(67,'P','Single source approval over Category Two','E',	1,	1)
,(68,'D','State Purchasing Agreement','C',	1,	1)
,(69,'B','State Term Contract Purchase with Request For Quotes from Qualified Vendors','C',	1,	1)
,(70,'A','State Term Contract Purchase without Request For Quotes from Qualified Vendors','C',	1,	1)
,(71,'36','State Board of Administration, whether directly or incidentally related to the investment or debt transactions, are exempt from the provisions of chapter 287. [s. 215.44(7), FS]','E',	1,	1)
,(72,'37','Leases less than 5,000 sq ft in a privately owned facility – may be obtained via quotes','C',	1,	1)
,(73,'38','Leases more than 5,000 sq ft in a privately owned facility – must be obtained through competitive procurement','C',	1,	1)
,(74,'39','Stay in Place/Replacement Lease – Fair Market Price Negotiations','C',	1,	1)
,(75,'40','Emergency Lease','E',	1,	1)
,(76,'41','State-Owned Office Building Lease through the Department of Management Services','C',	1,	1)
,(77,'42','Leases with federal agencies and other State/Local government entities','E',	1,	1)
,(78,'43','Request for Application method of competitively awarding State/Federal grants to for-profit organizations','C',	1,	1)
,(79,'44','Non-competitively awarded grants to governmental entities, non-profits or for-profit organizations','E',	1,	1)
	
	) seed ([ProcurementMethodId], [Code],[ProcurementMethodDescription],Exemption,ProcurementDocumentRequired,Active)
		ON Env.[ProcurementMethodId] = seed.[ProcurementMethodId]

WHEN NOT MATCHED BY TARGET THEN
	INSERT ([ProcurementMethodId], [Code],[ProcurementMethodDescription],Exemption,ProcurementDocumentRequired,Active)
	VALUES ([ProcurementMethodId], [Code],[ProcurementMethodDescription],Exemption,ProcurementDocumentRequired,Active);
GO 

SET IDENTITY_INSERT [dbo].[ProcurementMethods] OFF
GO